### PR TITLE
Run linter on changes in PRs

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
This PR will have a github action running the linter. It will probably take a few tries to see it working.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Currently blocked by https://github.com/dune-universe/duniverse-lint/pull/6 as the linter just always returns `0`.

**Comment by Leonidas-from-XIV** [comment]
The change to `asetmap` is just there to trigger it to run on a failing package and is to be removed before merging.

**Comment by Leonidas-from-XIV** [comment]
That's a good point. Yes, it made a bug apparent where the first package to fail would stop the linting it its tracks and cause the check to fail immediately. I changed the code that it runs the linter on all packages before determining whether it failed or not, that should show all the issues.

**Review by NathanReb — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
