### PR TITLE
add a mirror of charInfo_width using git

### PR DESCRIPTION
**Pull request by avsm**
there is no actual changes here, but this mirror is a convenience
until we fix avsm/duniverse#61 and support Mercurial dev repos

### CODE REVIEW

**Comment by Julow** [comment]
Duniverse fails with

```
duniverse: Multiple refs share the name 1.1.0 on the remote git://github.com/dune-universe/charinfo_width.git
```

The refs on the remote are

```
a8e701d9e7bb0791d0fdcc2d9ba700d1edb3fa03        HEAD
a8e701d9e7bb0791d0fdcc2d9ba700d1edb3fa03        refs/heads/master
a8e701d9e7bb0791d0fdcc2d9ba700d1edb3fa03        refs/import/heads/master
2c6ed768750660162009ba294c236f4356a5964a        refs/import/tags/0.1.0
9561b476050d181883379585c03eea7d6a36d080        refs/import/tags/1.0.0
5e8265d817a7b1a6f6fe4dfed4d584dc1e748bdb        refs/import/tags/1.1.0
2c6ed768750660162009ba294c236f4356a5964a        refs/tags/0.1.0
9561b476050d181883379585c03eea7d6a36d080        refs/tags/1.0.0
5e8265d817a7b1a6f6fe4dfed4d584dc1e748bdb        refs/tags/1.1.0
```

**Comment by NathanReb** [comment]
Hmm interesting, maybe we can improve that on the duniverse side as well, that seems to be due to the mercurial import. Would you mind opening an issue about that on duniverse?

**Comment by Julow** [comment]
Maybe that's a legitimate error ? Otherwise what should duniverse do between choosing the branch or the tag ?
Anyway, to avoid ambiguity we should push a `duniverse-vA.B.C` branch.

**Comment by NathanReb** [comment]
It's not a branch vs tag issue but one with repos imported from a different VCS into git. In this case we could just discard the tag from `refs/import` and use the one in `refs/tags`.

**Comment by Julow** [comment]
You are right, `refs/import/tags/*` are not even seen as branch by git. It seems that branches are always in `refs/heads` and tags in `refs/tags` so maybe we could use that to filter everything else in `refs/` ?

**Pull request merged**
