### PR TITLE
Remove seq as the upstream now uses dune

### PR DESCRIPTION
**Pull request by NathanReb**
I was expecting it not to work at first because the dune port was released as `0.2` with a `ocaml<4.07.0` constraint. That results in the `base` version being picked up and being treated as a virtual package by `duniverse` (indeed it has no `url.src` field) meaning `seq` isn't pulled in the duniverse and there's therefore no `seq` library, which I expected to trigger a dune error.

It turns out this works because there is a special case for that in `dune`, see https://github.com/ocaml/dune/pull/1714.

I'm not sure why this was added to dune as `seq.base` provides a `META`. I guess this must not have always been the case.

@rgrinberg can you remember why this is and/or was required?

Anyway we can safely remove this package and delete the fork!

### CODE REVIEW

**Comment by rgrinberg** [comment]
I agree to remove this hack if we confirm that installing OCaml provides the necessary META file for this library. I’ve copied Nicolas regarding this as he knows more about this than me.

**Comment by c-cube** [comment]
@NathanReb I know very little about the duniverse, sorry. I'm happy if `seq` now using dune makes y'all's life simpler :slightly_smiling_face:

**Comment by NathanReb** [comment]
Sorry I got distracted and forgot about that.

@c-cube what would you think about releasing the current dune-port as `final`, without constraints on the version of OCaml?

That way it's always installed, regardless of the OCaml version one uses, it works fine within duniverses and we can remove the hack in dune.

**Comment by c-cube** [comment]
@NathanReb you mean a seq package that uses dune without version constraint, but doesn't do anything if OCaml > 4.07? PR welcome, I haven't followed what y'all have been doing on the duniverse.

**Pull request merged**
