### PR TITLE
Add uchar.0.0.2+dune2

### PR DESCRIPTION
**Pull request by emillon**

### CODE REVIEW

**Comment by emillon** [comment]
- this needs a release tarball
- git url needs not to point to my fork
- `0.0.2+dune` opam file needs to point to the tag (or better - release tarball), not branch
- the branch name is dune3 which is wrong

**Comment by maiste** [comment]
Hi @emillon,
Does this PR fix the issue with `duniverse` and `uchar` in the `libraries` stanza?

**Comment by emillon** [comment]
yes! I'm going to fix the release so that it works.

**Comment by maiste** [comment]
Great! Thanks :smile:

**Comment by emillon** [comment]
Etienne,
I'm closing that in favor of #123.
Etienne.

**Pull request closed without merging**
