### PR TITLE
Add uucp.14.0.0+dune

### PR DESCRIPTION
**Pull request by emillon**

### CODE REVIEW

**Comment by emillon** [comment]
I think a release tarball would be better.

**Comment by Leonidas-from-XIV** [comment]
Yes, could you please roll a tarball? dune-release should be somewhat helpful even if upstream doesn't use it.

**Comment by NathanReb** [comment]
The README has instructions on how to use dune-release for this. Please reach out if they are unclear or wrong.

**Comment by emillon** [comment]
Closed in favor of #124

**Pull request closed without merging**
