### PR TITLE
Update the release process in the README

### PR DESCRIPTION
**Pull request by NathanReb**

### CODE REVIEW

**Comment by NathanReb** [comment]
CC @hannesm this is a bit more accurate now!

**Review by Leonidas-from-XIV — COMMENTED** [review]
I think it is nice (though I wonder if dune-release could be somehow parametrized to automatically open a PR to this repo instead of `opam-repository` but given there's a bit of config and setup required that'd probably require a bit of work on the `dune-release` side).

What I would like to see here would be also some pointers how to port the existing build systems like `oasis/ocamlbuild`, `topkg/ocamlbuild`, `omake` to `dune`. Maybe some links to examples where this was done could be helpful?

**Comment by NathanReb** [comment]
> though I wonder if dune-release could be somehow parametrized to automatically open a PR to this repo instead of opam-repository but given there's a bit of config and setup required that'd probably require a bit of work on the dune-release side

You're actually right that it should work! I'll see if I can make it work!

> What I would like to see here would be also some pointers how to port the existing build systems like oasis/ocamlbuild, topkg/ocamlbuild, omake to dune. Maybe some links to examples where this was done could be helpful?

It would be nice indeed but would you mind if we do this as part of a separate PR? This information was not in the README previously so we're not losing anything and I think this update is long overdue so I'd rather not hold it back for this!

**Review by Leonidas-from-XIV — APPROVED** [review]
Sure, let's have this addition at a later point in time.

**Comment by NathanReb** [comment]
I updated the release instructions to make better use of dune-release!

**Pull request merged**
