### PR TITLE
Release carton on the same tag as other released packages of the same…

### PR DESCRIPTION
**Pull request by samoht**
… repo

### CODE REVIEW

**Comment by samoht** [comment]
`carton-*` and `git-*` come from the same repository but they are released in separate tarballs with different hashes. This is confusing for `opam-monorepo`. The easy fix is to make a new release of `carton` using the latest `git` tarball.

**Comment by hannesm** [comment]
I honestly find this rather ad-hoc -- so a fresh release of carton-* and git-* will lead to "opam-monorepo" being confused again? Isn't there a fix for "opam-monorepo"? Or will there be something in place that keeps the carton in this overlay up to date?

**Comment by samoht** [comment]
Yes - when building a monorepo you need to keep multi-package repository in sync. Before opam-monorepo 0.4 it was done in an ad-hoc way by choosing one of the archive (mostly) randomly. Now this is encoded in the dependency metadata.

So I would say we are now more honest about the constraints and less ad-hoc :-) 

Why is it an issue to release everything on the same tag? That's what the CI is testing anyway.

**Comment by samoht** [comment]
(Also: this will be subsumed by dune4 - ETA beginning of next year)

**Comment by hannesm** [comment]
It is great that this will be subsumed by dune 4 in 3 months. I'll take your word on that :)

In the meantime, there's a fresh release of carton and git -- and I wonder who is going to update this repository with the modified opam files (plus what the version numbering is supposed to be, in opam-repository we have carton 0.6.0 and 0.7.0 -- here we have 0.6.1).

It's also great to be more "honest", but it also shows that `opam-monorepo` is taking some shortcuts / depending on some invariants that are not always true for the opam-repository.

Really, I'm fine to update such opam files manually, but I fear that this repository is barely updated and maintained -- e.g. updates to the "zarith" package haven't been done for a while (also, brr and cmdliner are outdated), there's not much activity at the opened issues... Due to that missing activity and orphaned issues, I'm not very motivated to open new issues.

**Pull request merged**
