### PR TITLE
Add dunified ctypes

### PR DESCRIPTION
**Pull request by NathanReb**
Haven't touched `opam-overlays` in a while so a double check would be nice!

### CODE REVIEW

**Comment by NathanReb** [comment]
Ouh there's a fancy CI now! Neat!

**Comment by NathanReb** [comment]
It seems like the `reactiveData` fork's `duniverse-0.2.2` branch got deleted for some reason. Does that ring a bell?

**Comment by NathanReb** [comment]
Ok it got merged upstream but not released. Should I open a PR to pin it to the upstream master branch in the meantime?

**Comment by avsm** [comment]
Thanks, I've pinged the maintainers to cut a release as well.

**Pull request merged**
