### PR TITLE
add ppxfind by depending on findlib

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by NathanReb** [comment]
Isn't the upstream already dunified ? See https://github.com/diml/ppxfind/releases/tag/1.3

**Comment by NathanReb** [comment]
Hmm nevermind, got it, it's the `ocamlfind` vs `findlib` issue!

Shouldn't we try to move it back to `ocamlfind` here as well so that packages that depend on it would work? I guess that require fixing the dune port so it also includes the ocamlfind binary!

**Comment by avsm** [comment]
Yeah, but the separation is useful to help weed out direct binary invocations of `ocamlfind` _vs_ library uses of `findlib`.  So if it's just one or two packages like ppxfind that break, I think this approach is ok.

**Comment by avsm** [comment]
This fix is broken and doesn't compile; will try again

**Pull request closed without merging**
