### PR TITLE
[new release] topkg (1.0.5+dune)

### PR DESCRIPTION
**Pull request by emillon**
The transitory OCaml software packager

- Project page: <a href="https://github.com/dune-universe/topkg">https://github.com/dune-universe/topkg</a>

##### CHANGES:

- Remove mentions of `Result.result` in the code base. We got the
  dependency indirectly through `bos` and the latest version of the
  latter no longer depends on it.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Can you push your 1.0.5 branch to dune-universe/topkg? I can see the tagged commit there but no branch.

Yes, sorry about that linter error - I agree that it is fine and that we don't need topkg-care.

**Comment by NathanReb** [comment]
Out of curiosity, why do need topkg to be ported to dune?

**Comment by NathanReb** [comment]
I suspect we don't actually need it and that a dune port forgot to remove the topkg dependency but I might be wrong!

**Comment by NathanReb** [comment]
```
$ opam list --depends-on topkg --depends-on dune
# Packages matching: (installed | available) & depends-on(topkg) & depends-on(dune)
# No matches found
```

**Comment by emillon** [comment]
> Can you push your 1.0.5 branch to dune-universe/topkg? I can see the tagged commit there but no branch.

done!

**Comment by samoht** [comment]
it's indeed unclear why we need to package `topkg` at all. I recommend removing it and see what's breaks :p

**Comment by Leonidas-from-XIV** [comment]
@samoht Agreed, pushed a commit to remove all versions of `topkg`. Worst case we'll revert the commit if it proves to be a problem in the future.

**Pull request merged**
