### PR TITLE
[new release] note (0.0.2+dune)

### PR DESCRIPTION
**Pull request by dinosaure**
/cc @NathanReb & @Leonidas-from-XIV

### CODE REVIEW

**Review by Leonidas-from-XIV — APPROVED** [review]
Looks good!

**Comment by dinosaure** [comment]
I force-pushed and redo a release without the `s` in `note` into the OPAM file.

**Comment by dinosaure** [comment]
I'm not sure to understand the failure, I correctly append `+dune` :confused:

**Comment by Leonidas-from-XIV** [comment]
The linter looks into the unpacked tarball and checks for the `dune-project` file and the version. Here it is `(version v0.0.2-1-g64c9821)`

**Comment by dinosaure** [comment]
> The linter looks into the unpacked tarball and checks for the dune-project file and the version. Here it is (version v0.0.2-1-g64c9821)

I'm not sure how to properly fix this issue when `git describe` returns, indeed, `v0.0.2-1-g64c9821`. How to explain `dune subst` to put `v0.0.2+dune`?

**Comment by dinosaure** [comment]
I found the error, when we make a tag, we must do an *annotated* tag with `git tag -a`.

**Comment by Leonidas-from-XIV** [comment]
Usually we use `dune-release` which works extremely well on dbunzli's projects, and it creates an annotated tag by default when using `dune-release tag` and it also puts the changelog into the tag.

**Pull request merged**
