### PR TITLE
ppx_tools uses dune since 6.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
I don't think this can be merged, as it would break all lockfiles that depend on this version.

**Comment by Leonidas-from-XIV** [comment]
Ok, I was a bit too hasty, removing it won't break lockfiles since they don't need access to the overlays to work, so I deleted the comment.

That said, `ppx_tools+6.1+dev+dune` is actually a bit unusual since it has [some adjustments](https://github.com/dune-universe/ppx_tools/commits/v6.1%2Bdev%2Bdune) that are not part of ppx_tools 6.1 or 6.2, most notably [ab0a7d0bc4b87abed0c4f611d9aa30406c0d09b0](https://github.com/dune-universe/ppx_tools/commit/ab0a7d0bc4b87abed0c4f611d9aa30406c0d09b0) which potential users of opam-monorepo might require.

**Comment by kit-ty-kate** [comment]
Unless users of opam-monorepo cannot use cppo this is not a good reason.
Also, to my knowledge, no-one is using ppx_tools anymore.

**Comment by Leonidas-from-XIV** [comment]
> Unless users of opam-monorepo cannot use cppo this is not a good reason.

This is less about developers using CPPO, but more about the support for multiple compiler versions. If the lockfile and the users switch have different compiler versions they might fail which I assume is the reason why @avsm added this commit. Pulling a lockfile and have it fail immediately because ppx_tools does not support your compiler version is a pretty bad user experience.

That said, patching every library to have versions for every OCaml compiler version is problematic too, especially as this version of ppx_tools only supports OCaml 4.12 at max.

> Also, to my knowledge, no-one is using ppx_tools anymore.

This is the problem with it - we don't know. Github doesn't have statistics and the only way we learn about breakage is users reporting it (if they do and don't just dismiss the tool as "broken and useless").

**Comment by kit-ty-kate** [comment]
Anil's commit is simply an old version (6.2) that was iterated upon in 6.3 using cppo. They all support the same versions. Trust me I'm the maintainer..

**Comment by Leonidas-from-XIV** [comment]
Ok. Given that old lockfiles will continue to work as long as we keep the tarball around and new lockfiles should use 6.3+ anyway, it makes sense to me now.

**Pull request merged**
